apiVersion: v1
kind: Service
metadata:
  name: motivate
  namespace: motivate
  labels:
    app: motivate
spec:
  type: ClusterIP
  selector:
    app: motivate
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080